[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@morpho-blue/=lib/morpho-blue/src/",
    "@metamorpho-v1.1/=lib/metamorpho-v1.1/src/"
]

[rpc_endpoints]
eden = "https://ev-reth-eden-testnet.binarybuilders.services:8545"

[fmt]
line_length = 100

