[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@morpho-blue/=lib/morpho-blue/src/"
]

[rpc_endpoints]
sepolia = "http://localhost:8545"

[fmt]
line_length = 100

